---
swagger: "2.0"
info:
  version: 1.0-SNAPSHOT
  title: lesson 1
basePath: /v1
paths:
  /accounts:
    post:
      description: Create Account
      operationId: accounts/createAccount
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: "#/definitions/Account"
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        201:
          description: response
          schema:
            $ref: "#/definitions/Account"

    get:
      description: Query for accounts by customerId
      operationId: accounts/queryAccounts
      parameters:
      - in: query
        name: customerId
        type: integer
        description: Customer Id
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: response
          #schema:
          #  $ref: "#/definitions/AccountList"
          
  /accounts/{id}:
    get:
      description: Get Account Balances
      operationId: accounts/getBalance
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          description: response
          schema:
            $ref: "#/definitions/Account"

definitions:
  Account:
    type: object
    properties:
      balance:
        type: integer
      id:
        type: integer
      label:
        type: string
      type:
        type: string
        enum:
        - checking
        - savings
